sudo: false
language: php
php:
  - 5.6
  - 7.0

install:
  - sh -c "cd update-server/ && composer install"

before_script:
  - php -S localhost:8888 update-server/index.php &


script:
  - sh -c "cd update-server/tests/integration/ && ../../vendor/bin/behat ."
  - sh -c "cd update-server/tests/unit/ && phpunit ."
