sudo: false
language: php
php:
  - 7.1
  - 7.2
  
install:
  - sh -c "cd update-server/ && composer install"

before_script:
  - php -S localhost:8888 update-server/index.php &


script:
  - sh -c "cd update-server/tests/integration/ && ../../vendor/bin/behat ."
  - sh -c "cd update-server/tests/unit/ && ../../vendor/bin/phpunit ."
